#!/bin/sh /etc/rc.common

start_service() {
	local FUNCTION=$(uci get button-bind.wifi.function)
	if [ "${FUNCTION}" = 3 ]
	then
		for i in /sys/class/leds/* ; do echo 0 > "$i"/brightness ; done
	fi
}
