#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50

start_service() {
	[ -e /tmp/ffmyk_radvd_arguments ] || return 1

	procd_open_instance
	procd_set_param command /usr/sbin/uradvd $(cat /tmp/ffmyk_radvd_arguments)
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_close_instance
}
