include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-config-mode-qrcode
PKG_VERSION:=1

PKG_BUILD_DIR := $(BUILD_DIR)/$(PKG_NAME)

include $(TOPDIR)/../package/gluon.mk

define Package/gluon-config-mode-qrcode
  TITLE:=Display node registration link as QR-Code 
endef

$(eval $(call BuildPackageGluon,gluon-config-mode-qrcode))
